name: deploy to heroku

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: checkout backend
        uses: actions/checkout@v2
        with:
          repository: Couch-Coders/6th-music-be
          path: ./
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: checkout frontend
        uses: actions/checkout@v2
        with:
          path: ./frontend
      - name: build frontend to resources
        run: |
          cd frontend
          rm package-lock.json
          npm install
          npm run build
          cd ..
          cp -r frontend/build/* src/main/resources/static/
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "codingyo"
          heroku_email: "vel1024@naver.com"